# Generated by Django 4.2.1 on 2023-05-17 02:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
        ('travel_app', '0002_destination_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel_app.destination'),
        ),
        migrations.AddField(
            model_name='review',
            name='time_commented',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tour',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authen.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.user'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel_app.destination'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
