# Generated by Django 4.2.1 on 2023-05-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_remove_review_tour_remove_tour_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
